import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
import os
import logging
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

logger = logging.getLogger(__name__)

# Email configuration
SMTP_SERVER = os.getenv("SMTP_SERVER", "smtp.gmail.com")
SMTP_PORT = int(os.getenv("SMTP_PORT", "587"))
EMAIL_USER = os.getenv("EMAIL_USER", "")  # Your email
EMAIL_PASSWORD = os.getenv("EMAIL_PASSWORD", "")  # App password
RECIPIENT_EMAILS = os.getenv("RECIPIENT_EMAILS", "vhschahal@gmail.com").split(",")

def send_fault_email(fault_data: dict) -> bool:
    """Send email notification for fault detection to multiple recipients"""
    if not EMAIL_USER or not EMAIL_PASSWORD:
        logger.warning("Email credentials not configured, skipping email notification")
        return False
    
    if not RECIPIENT_EMAILS:
        logger.warning("No recipient emails configured, skipping email notification")
        return False

    # Clean up recipient emails (remove whitespace)
    recipients = [email.strip() for email in RECIPIENT_EMAILS if email.strip()]
    
    if not recipients:
        logger.warning("No valid recipient emails found, skipping email notification")
        return False

    # Email body template
    body_template = """
    <html>
    <body>
        <h2 style="color: #d32f2f;">⚡ FAULT ALERT - IoT Pole Monitoring System</h2>
        
        <div style="background-color: #ffebee; padding: 20px; border-left: 5px solid #d32f2f; margin: 20px 0;">
            <h3>Fault Details:</h3>
            <ul>
                <li><strong>Pole ID:</strong> {node_id}</li>
                <li><strong>Fault Type:</strong> {description}</li>
                <li><strong>Confidence Level:</strong> {confidence:.1f}%</li>
                <li><strong>Detected At:</strong> {reported_at}</li>
                <li><strong>Status:</strong> <span style="color: #d32f2f; font-weight: bold;">FAULTY</span></li>
            </ul>
        </div>

        <div style="background-color: #fff3e0; padding: 15px; border-left: 5px solid #ff9800; margin: 20px 0;">
            <h4>⚠️ Immediate Action Required:</h4>
            <p>A fault has been detected in the electrical pole monitoring system. Please dispatch maintenance team immediately to investigate and resolve the issue.</p>
        </div>

        <div style="background-color: #f3e5f5; padding: 15px; border-left: 5px solid #9c27b0; margin: 20px 0;">
            <h4>📱 System Information:</h4>
            <p>This alert was automatically generated by the IoT Pole Fault Monitoring System. Staff members have been notified via mobile app notifications.</p>
        </div>

        <hr style="margin: 30px 0;">
        <p style="color: #666; font-size: 12px;">
            <em>This is an automated message from IoT Pole Monitoring System. Please do not reply to this email.</em><br>
            <strong>System Time:</strong> {reported_at}<br>
            <strong>Alert ID:</strong> FAULT-{fault_id}
        </p>
    </body>
    </html>
    """

    body = body_template.format(
        node_id=fault_data['node_id'],
        description=fault_data['description'],
        confidence=fault_data['confidence'],
        reported_at=fault_data['reported_at'],
        fault_id=fault_data.get('id', 'N/A')
    )

    successful_sends = 0
    failed_sends = 0

    # Send email to each recipient individually
    for recipient in recipients:
        try:
            # Create individual message for each recipient
            msg = MIMEMultipart()
            msg['From'] = EMAIL_USER
            msg['To'] = recipient
            msg['Subject'] = f"⚡ URGENT: Fault Detected in Pole {fault_data['node_id']}"
            msg.attach(MIMEText(body, 'html'))

            # Send email
            with smtplib.SMTP(SMTP_SERVER, SMTP_PORT) as server:
                server.starttls()
                server.login(EMAIL_USER, EMAIL_PASSWORD)
                text = msg.as_string()
                server.sendmail(EMAIL_USER, recipient, text)

            logger.info(f"Fault email sent successfully to {recipient}")
            successful_sends += 1

        except Exception as e:
            logger.error(f"Failed to send fault email to {recipient}: {str(e)}")
            failed_sends += 1

    # Return True if at least one email was sent successfully
    total_attempts = successful_sends + failed_sends
    logger.info(f"Email notification summary: {successful_sends}/{total_attempts} emails sent successfully")
    
    return successful_sends > 0



def send_fault_notification(fault_data: dict) -> bool:
    """Send email notification for fault detection"""
    try:
        # Send email notification
        email_sent = send_fault_email(fault_data)
        
        logger.info(f"Fault email notification sent: {email_sent}")
        
        return email_sent
        
    except Exception as e:
        logger.error(f"Error sending fault notification: {str(e)}")
        return False